"""Update News

Revision ID: 15defa030535
Revises: 
Create Date: 2024-10-01 22:30:14.282658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15defa030535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsync_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_end', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('created_at')
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsync_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('completed')
        batch_op.drop_column('time_end')

    # ### end Alembic commands ###
