"""Update DB

Revision ID: 75635da4f8d8
Revises: 15defa030535
Create Date: 2024-10-06 21:59:39.965563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75635da4f8d8'
down_revision = '15defa030535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsync_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backuptime', sa.String(), nullable=False))
        batch_op.drop_column('time_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsync_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_end', sa.DATETIME(), nullable=False))
        batch_op.drop_column('backuptime')

    # ### end Alembic commands ###
